export const SAVE_ACTION = 'REDUX_LIVE_SAVE_ACTION';
export const SUBSCRIBE_TO_STREAM = 'REDUX_LIVE_SUBSCRIBE_TO_STREAM';
export const UNSUBSCRIBE_TO_STREAM = 'REDUX_LIVE_UNSUBSCRIBE_TO_STREAM';
export const NEW_ACTION = 'REDUX_LIVE_NEW_ACTION';
