export const CONFIRM_ACTION = 'REDUX_LIVE_CONFIRM_ACTION';
export const UNSUBSCRIBE_TO_STREAM = 'REDUX_LIVE_UNSUBSCRIBE_TO_STREAM';
export const SUBSCRIBE_TO_STREAM = 'REDUX_LIVE_SUBSCRIBE_TO_STREAM';
